### ISSUE TITLE
Personalization

### ISSUE THREAD

**Issue by davidcamick** [KdogDevs/schedulesspx#11]
Ability to add your own google image/uploaded image as a background or change the colors to anything you want

Could be like a customize tab in your account page, like a place to upload an image that is stored in cookies, and color selector would also be stored in cookies, just a simple clean color picker. Could be any color you want or like a color palette

From people in math class

**Comment by KdogDevs** [comment]
Add themes for major holidays and 6 separate themes and maybe feats days
